### ISSUE TITLE
Replace Enum containing valid fields of study

### ISSUE THREAD

**Issue by nklsd** [upb-uc4/hlf-chaincode#33]
**Is your feature request related to a problem? Please describe.**
Handling the valid fields of study in a hard-coded enum embedded in the chaincode is a hard to maintain solution und not very user friendly.

**Describe the solution you'd like**
We need a solution which is better to maintain und easier to configure, such as entries on the chain, which specify valid fields of study. 

**Additional context**
The wanted solution is not final, but yet an idea to discuss.

**Comment by matthias-geuchen** [comment]
Should we have a chaincode for fields of study (i.e.) store fields of study on chain and perform checks for matriculation data in MatriculationData contract, or just store arbitrary strings in MatriculationData's fieldOfStudy fields without checking?

**Comment by nklsd** [comment]
I think we should not just store arbitrary strings. If we dont want to implement checks on our own, we would have to rely on checks on lagom/vue side of the project or solely rely on correct user input, respectively.
So i think we should maybe have a chaincode with checks in the MatriculationData for this, like @matthias-geuchen said.
