### ISSUE TITLE
Extend Group Contract 

### ISSUE THREAD

**Issue by mco33415** [upb-uc4/hlf-chaincode#96]
Extend Group Contract  to contain environment variables.

**Comment by NikoBergemann** [comment]
Paul proposed a new solution.
The ScalaAdmin is created with a hyperledger_group ("attr" sysAdmin=true).
We can maybe access the attr. with getClientIdentity().getAttribute() or in the certificate

**Comment by this-kramer** [comment]
> @this-kramer proposed a new solution.
> The ScalaAdmin is created with a hyperledger_group ("attr" sysAdmin=true).
> We can maybe access the attr. with getClientIdentity().getAttribute() or in the certificate

See https://github.com/upb-uc4/hlf-network/pull/109

**Comment by this-kramer** [comment]
> > @this-kramer proposed a new solution.
> > The ScalaAdmin is created with a hyperledger_group ("attr" sysAdmin=true).
> > We can maybe access the attr. with getClientIdentity().getAttribute() or in the certificate
> 
> See [upb-uc4/hlf-network#109](https://github.com/upb-uc4/hlf-network/pull/109)

Merged into develop
